export const START_LOADER = 'START_LOADER';
export const STOP_LOADER = 'STOP_LOADER';

export const FETCH_VIDEO_CONTENT = 'FETCH_VIDEO_CONTENT';
export const UPDATE_VIDEO_CONTENT = 'UPDATE_VIDEO_CONTENT';

