export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const UPDATE_ITEMS = 'UPDATE_ITEMS';
export const UPDATE_SELECTED_ITEM = 'UPDATE_SELECTED_ITEM';
export const START_LOADER = 'START_LOADER';
export const STOP_LOADER = 'STOP_LOADER';

